### ISSUE TITLE
Source for the README Quote

### ISSUE THREAD

**Issue by ekmett** [domdere/fp-in-idris#1]
The actual quote is

> If scala was the only language I had to think in, I'd think functional programming was a bad idea that didn't scale, too.

It came from [this comment](http://www.reddit.com/r/haskell/comments/1pjjy5/odersky_the_trouble_with_types_strange_loop_2013/cd3bgcu) on reddit.

**Comment by domdere** [comment]
resolved in #2 ?

**Comment by ekmett** [comment]
Yep.
